//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagementApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Appartment
    {
        public int AppartmentId { get; set; }


        [DisplayName("Unit Number")]
        [Required]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Only digits are allowed.")]
        public int UnitNumber { get; set; }


        [DisplayName("Number of Bedroom")]
        [Required]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Only digits are allowed.")]
        public int BedRoomNumber { get; set; }

        [Required]
        [RegularExpression("^(?i)(Yes|No)$", ErrorMessage = "Please enter 'Yes' or 'No'.")]
        public string Furnished { get; set; }
        public int BuildingId { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
