//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagementApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Building()
        {
            this.Appartments = new HashSet<Appartment>();
        }
    


        public int BuildingId { get; set; }


        [Required, MaxLength(50)]
        public string Address { get; set; }

        [DisplayName("Building Name")]
        [Required, MaxLength(50)]
        public string BuildingName { get; set; }

        [DisplayName("Total Floors")]
        [Required]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Only digits are allowed.")]
        public int TotalFloors { get; set; }

        [DisplayName("Allow Pet")]
        [Required]
        [RegularExpression("^(?i)(Yes|No)$", ErrorMessage = "Please enter 'Yes' or 'No'.")]
        public string AllowPet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appartment> Appartments { get; set; }
    }
}
